### ISSUE TITLE
Library available in maven?

### ISSUE THREAD

**Issue by Maikell84** [zh-wang/YWeatherGetter4a#19]
Hello,

Is this library available in Maven?
If so, what URL do we have to put in the build.gradle file?
If not, will it be? ;)

Best regards
Michael

**Comment by zh-wang** [comment]
Not available in Maven yet. I really don't know how to put it on Maven.
2015/07/20 午後4:24 "Maikell84" <notifications@github.com>:

**Comment by Maikell84** [comment]
Thank you for your answer. I found a way to include the repository in maven:

    repositories {
        maven {
            url "https://jitpack.io"
        }
    }
    dependencies {
        compile 'com.github.zh-wang:YWeatherGetter4a:745367a404@aar'
    }
