### ISSUE TITLE
Problem getting woeid from gps location

### ISSUE THREAD

**Issue by denite** [zh-wang/YWeatherGetter4a#20]
This wrapper was working great, but just stopped all of the sudden. I was using weather by GPS... 

I think the problem has to do with the class WOEIDUtils... It's not returning any results...

If I just try the url to get the woeid, I get this in a browser…

http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20geo.placefinder%20where%20text%3D%2249.2815476%2C-123.1314869%22%20and%20gflags%3D%22R%22

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<query xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" yahoo:count="0" yahoo:created="2016-01-22T03:58:19Z" yahoo:lang="en-US">
<results/>
</query>

Is there something special I need to do to enable this?

It would be great if I could get this working.

Thanx so much for your time.

**Comment by zh-wang** [comment]
It seems that Yahoo has moved Geo.Placefinder to BOSS service, which is not free. So query woeid from GPS(or you can call it "Reverse Geocoding") location will not work for FREE any more.

**Comment by zh-wang** [comment]
You can use https://github.com/googlemaps/google-maps-services-java to do "Reverse Geocoding". But it is a large chunk of code, so I won't use it in my project. What you need to is, use Google Map's api to get the place name by GPS location. Then query Yahoo Weather API with the place name. Hope it helps.

**Comment by denite** [comment]
Thanx for looking into this for me, I appreciate it!

 

That’s exactly what I ended up doing… looking up the city name from the lon, lat… and getting the weather from that… I figured that out the other day… ;-)

 

Thanx for putting this wrapper together!! I really appreciate it!

 

DeNitE!

**Comment by zh-wang** [comment]
I have changed reverse geocoding from Yahoo's api to Android's Geocoder.
