### ISSUE TITLE
OST_OAUTH_PARAMETER_ABSENT_ERROR

### ISSUE THREAD

**Issue by denite** [zh-wang/YWeatherGetter4a#21]
Looks like Yahoo in enforcing authentication now... :-(

Suggestions on how to implement this?

**Comment by zh-wang** [comment]
It seems that 'http://weather.yahooapis.com/forecastrss?w=2151849&u=c' won't work anymore. Maybe it's the time to use their new apis. 

https://developer.yahoo.com/weather/https://developer.yahoo.com/weather/

**Comment by denite** [comment]
This works...

        String queryUrl = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%3D" + woeidNumber + "&diagnostics=true";

**Comment by zh-wang** [comment]
However, it uses public syntax so i think it will be disabled sooner or later

**Comment by denite** [comment]
Ya... I'm scared of that. Any idea how to incorporate my app id and secret code? I can't figure it out...

**Comment by davidmonti** [comment]
Same problem here, but I have a client id and secret, how to use them to get it running again?

**Comment by usmanhashmi2123** [comment]
@zh-wang  Waiting for update in the wrapper.
I have client Id and Secret key but don,t know how to use them in this wrapper.

**Comment by zh-wang** [comment]
I have updated weather api's endpoint, which is still can be accessed by 'public' keyword. An OAuth version will be updated later.

**Comment by denite** [comment]
Thanx for your work on this @zh-wang. It's appreciated!!
